version: '3.9'
services:
  app:
    container_name: name-app-prd
    env_file:
      - .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prd
    ports:
      - ${PORT}:${PORT}
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST: name-mongodb-prd
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_RESET_PASSWORD_KEY: ${JWT_SECRET_RESET_PASSWORD_KEY}
      JWT_SECRET_CONFIRM_ACCOUNT_KEY: ${JWT_SECRET_CONFIRM_ACCOUNT_KEY}
    depends_on:
      - name-mongodb-prd

    networks:
      - name-mongodb-network-prd

  name-mongodb-prd:
    container_name: name-mongodb-prd
    restart: unless-stopped
    image: mongo:latest
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - name-mongodb-data-prd:/data/db
      - name-mongodb-logs-prd:/var/log/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - name-mongodb-network-prd

networks:
  name-mongodb-network-prd:
    driver: bridge

volumes:
  name-mongodb-data-prd:
  name-mongodb-logs-prd:
