# Etapa base: Usamos node:20-alpine
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install --legacy-peer-deps

# Eliminar la carpeta `dist` si existe
RUN rm -rf dist

# Copiar el resto de los archivos
COPY . .

# Construir el proyecto
RUN npm run build

# Exponer el puerto 3000
EXPOSE 3000

# Comando de inicio
CMD ["node", "dist/main.js"]
